let songInfo = { 
	title: 'Dog-Like Sparky',
	lyrics: [
		"You ever believed in BIG STRONG DADDY LEGS?",
		"And do you believe in BAD FLYING AEROPLANE?",
		"Then you will REJOICE in believing in DOG-LIKE SPARKY!",
		"He's all heaven sent but will he suffer from your sweetness",
		"If I am a DOG then shake hands brother, sis'",
		"We'll never ever sing like Barky",
		"We wanna be Dog-like Sparky",
		"No feet for me and suck red upon my belly",
		"We wanna be DOG-LIKE SPARKY",
		"",
		"Defenders of the world we make believe in",
		"Put your hands on the Holy Bible and scream wank",
		"If I am a dog then shake hands brother, sis'",
		"We'll never ever sing like Barky",
		"We wanna be Dog-like Sparky",
		"No feet for me and suck red upon my belly",
		"We wanna be DOG-LIKE SPARKY",
		"",
		"Stay alive without or without praising him off his pins",
		"That glisten wheel-like in their shining wheely tins",
		"Never mind as crawling is my in mind world with everything alive",
		"Stick and suck dribble in my dirty shoes",
		"And crown me 'EVERYTHING ALIVE'",
		"",
		"And so the spirits they do protect him now",
		"Where he is all spoiled",
		"Where he's too SQUASHED AND HURT BY FEELINGS",
		"Now eat up your hand now eat your...",
		"",
		"Brother, sis' we'll never ever sing like Barky",
		"We wanna be Dog-like Sparky",
		"No feet for me and suck red upon my belly",
		"We wanna be DOG-LIKE SPARKY",
		"No feet for me and suck red upon my belly",
		"No feet for me and suck red upon my belly",
		"",
		"Never mind as crawling is my in mind world with everything alive",
		"Stick and suck dribble in my dirty shoes",
		"And crown me 'EVERYTHING ALIVE'",
		"Stick and suck dribble in my shoes",
		"And crown me 'EVERYTHING ALIVE'",
		"Stick and suck dribble in my dirty shoes",
		"And crown me 'EVERYTHING ALIVE'",
		"",
		"Is me alive and a-crawling?",
		"Is my world?",
		"Crawling is my world!",
		"Crawling is my world!",
		"Is me alive and a-crawling?",
		"Is my world?",
		"Crawling is my world!",
		"Crawling is my world!",
		"",
		"And so the spirits they do protect him now",
		"Where he is all spoiled",
		"Where he's too SQUASHED AND HURT BY FEELINGS",
		"If I am a dog then shake hands brother, sis'",
		"We'll never ever sing like Barky",
		"We wanna be Dog-like Sparky",
		"No feet for me and suck red upon my belly",
		"We wanna be DOG-LIKE SPARKY",
		"Brother, sis' we'll never ever sing like Barky",
		"We wanna be Dog-like Sparky",
		"No feet for me and suck red upon my belly",
		"We wanna be DOG-LIKE SPARKY",
		"Brother, sis' we'll never ever sing like Barky",
		"We wanna be Dog-like Sparky",
		"No feet for me and suck red upon my belly",
		"We wanna be DOG-LIKE SPARKY",
		"Brother, sis' we..."
	],
	navbox: {
		file: 'stg.jpg',
		caption: 'See Guns cover',
		info: [{
			heading: 'Information',
			info: [{
				name: 'Album',
				info: ['Sing To God']
			}, {
				name: 'Song Number',
				info: ['3']
			}, {
				name: 'Previous',
				info: ['<a href="index.html?s=stg-wormsHero">Eat It Up Worms Hero</a>']
			}, {
				name: 'Next',
				info: ['<a href="index.html?s=stg-fieryGunHand">Fiery Gun Hand</a>']
			}]
		}]
	}
};
